version: "3"

networks:
  prodnetwork:
    driver: bridge

services:
# Nexus
  nexus:
    image: sonatype/nexus3:latest
    ports:
      - "18081:8081"
      - "18082:8082"
      - "18083:8083"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - prodnetwork
# Sonar
  sonar:
    build: ./sonar
    ports:
      - "19000:9000"
    networks:
      - prodnetwork
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-conf:/opt/sonarqube/conf
    depends_on:
      - sonardb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
  sonardb:
    networks:
      - prodnetwork
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonardb-data:/var/lib/postgresql/data
      - sonardb:/var/lib/postgresql
# Jenkins
  jenkins:
    build: ./jenkins
    ports:
      - "18080:8080"
    networks:
      - prodnetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - nexus
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
# Selenium
  seleniumhub:
    image: selenium/hub
    ports:
      - "4444:4444"
    networks:
      - prodnetwork
  firefox:
    image: selenium/node-firefox
    depends_on:
      - seleniumhub
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
    networks:
      - prodnetwork
  chrome:
    image: selenium/node-chrome
    depends_on:
      - seleniumhub
    environment:
      - HUB_PORT_4444_TCP_ADDR=seleniumhub
    networks:
      - prodnetwork


volumes:
  nexus-data:
  sonar-data:
  sonar-conf:
  sonar-logs:
  sonardb-data:
  sonardb:
  jenkins-data:
