version: "3"

networks:
  prodnetwork:
    driver: bridge

services:
  nexus:
    # build: ./nexus
    image: sonatype/nexus:latest
    ports:
      - "18081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - prodnetwork

  sonar:
    build: ./sonar
    ports:
      - "19000:9000"
    networks:
      - prodnetwork
    volumes:
      - sonar-data:/opt/sonarqube/data
      - sonar-conf:/opt/sonarqube/conf
    depends_on:
      - sonardb
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
  sonardb:
    networks:
      - prodnetwork
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - sonardb-data:/var/lib/postgresql/data
      - sonardb:/var/lib/postgresql

  jenkins:
    build: ./jenkins
    ports:
      - "18080:8080"
    networks:
      - prodnetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - nexus
      - sonar
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432

volumes:
  nexus-data:
  sonar-data:
  sonar-conf:
  sonar-logs:
  sonardb-data:
  sonardb:
  jenkins-data:
